# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2009252fa49dd89ec8f99706b0fff155c572ff6a67f325fa12d779d28f80c8dd2348007bc8f32809dd4ed57dd7825659acebfc995cc73d7a476c507f7c36a1a

test:
  secret_key_base: cdbfe38e85ec220a1b2df4a52d0e64df99a2e2528d3e66dfd7c4c393960d91d83677742205388e13b0b70aa8b9cbd8a96526b19931c8c055ae0839e47f84f4c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
